version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: telegram_bot_db
    environment:
      POSTGRES_DB: telegram_bot_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5349:5432"
